CREATE DATABASE TASK;
USE TASK;
CREATE TABLE LAPTOP(
PROD_ID INT,
PROD_NAME varchar(30),
PROD_INFO varchar(90),
PROD_PRICE INT ,
PROD_ORIGIN varchar(20),
PROD_ADDRESS varchar(60),
PROD_BATTERYCAPASITY varchar(40),
PROD_STORAGE varchar(70),
PROD_RAM varchar(30),
PROD_VERSION  varchar(30)
);

CREATE TABLE MOBILE(
MOBILE_BRANDNAME varchar(70),
MOBILE_SERIES varchar(30),
MOBILE_FEATURE varchar(60),
MOBILE_PRICE INT,
MOBILE_STORAGE varchar(10),
MOBILE_ORIGIN varchar(50),
MOBILE_MANUFACTUREDATE DATE ,
MOBILE_ID INT,
MOBILE_IMEI INT ,
MOBILE_BATTERYCAPACITY varchar(45)
);

CREATE TABLE JUICE_CENTER(
CENTER_NAME varchar(100),
CENTER_OWNERNAME varchar(36),
FRUIT_NAME varchar(47),
FRUIT_QUANTITY varchar(30),
FRUIT_PRICE INT ,
LOCATION varchar(50),
JUICE_TYPE varchar(34),
ICE varchar(73),
JUICE_USE varchar(35),
FRUIR_SEASON varchar(45)
);

CREATE TABLE SHOES(
BRAND_NAME varchar(58),
CLOSURE_TYPE varchar(45),
HEEL_TYPE varchar(65),
WATER_RESISTANCE varchar(67),
SOLE_MATERIAL varchar(45),
STYLE varchar(34),
COUNTRY_OF_OROGIN varchar(90),
PRICE INT,
WEIGHT varchar(45),
DIMENSION varchar(65) 
);

SHOW TABLES;

CREATE TABLE WATCH(
BRAND_NAME varchar(74),
PRICE INT,
COLOUR varchar(65),
MATERIAL_TYPE varchar(34),
WEIGHT varchar(74),
COUNTRY_OF_ORIGIN varchar(54),
CASE_DIAMETER varchar(54),
MANUFACTURER varchar(99),
GENERIC_NAME varchar(54),
WARRANTY varchar(64)
);

CREATE TABLE MENSHORTS(
MATERIAL varchar(45),
STYLE varchar(83),
LENGTH varchar(34),
FIT_TYPE varchar(28),
MANUFACTURE varchar(37),
CARE_INSTRUCTION varchar(54),
COUNTRY_OF_ORIGIN varchar(54),
PRICE INT,
WEIGHT varchar(49),
QUANTITY INT
);

CREATE TABLE JEWELLERY(
CLASP_TYPE varchar(73),
MATERIAL varchar(65),
METAL_TYPE varchar(43),
CHAIN_TYPE varchar(32),
GEM_TYPE varchar(83),
OCCASION_TYPE varchar(43),
COUNTRY_OF_ORIGIN varchar(82),
PRICE INT,
WEIGHT varchar(27),
QUANTITY varchar(86)
);

CREATE TABLE WALLET(
BRAND varchar(46),
COLOR varchar(39),
MATERIAL varchar(20),
STYLE varchar(49),
PATTERN varchar(28),
DIMENSION varchar(36),
COUNTRY_OF_ORIGIN varchar(48),
PRICE INT,
QUANTITY varchar(34),
WEIGHT varchar(26)
);

CREATE TABLE HOTEL(
HOTEL_NAME varchar(35),
HOTEL_LOCATION varchar(27),
SNACKS varchar(36),
MAINCOURSE varchar(25),
VEG varchar(27),
NON_VEG varchar(39),
STARTER varchar(83),
DESSERT varchar(72),
PRICE INT,
THALI varchar(63)
);

CREATE TABLE LASSI_SHOP(
LOCATION varchar(75),
OWNER_NAME varchar(63),
BURGER varchar(45),
SANDWITCH varchar(52),
PIZZA varchar(92),
LASSI varchar(64),
PRICE INT,
JUICE varchar(38),
MOCKTAIL varchar(54),
ICE_CREAM varchar(43)
);

ALTER TABLE LASSI_SHOP RENAME  TO PIZZA_HUT;
ALTER TABLE LAPTOP RENAME COLUMN  PROD_ID TO DETAILS  ;
ALTER TABLE MENSHORTS ADD COLUMN ADDIDAS varchar(49);
ALTER TABLE SHOES DROP COLUMN STYLE  ;
ALTER TABLE WATCH DROP column COLOUR , DROP COLUMN  PRICE , DROP COLUMN WEIGHT;
ALTER TABLE JEWELLERY ADD COLUMN SILVER varchar(32) , ADD COLUMN GOLD VARCHAR (55);
ALTER TABLE JUICE_CENTER MODIFY COLUMN CENTER_NAME VARCHAR (50) ;
ALTER TABLE HOTEL MODIFY COLUMN PRICE varchar(53);
ALTER DATABASE TASK MODIFY NAME = PROJECT;


